model:
  class_path: anomalib.models.AiVad
  init_args:
    box_score_thresh: 0.8
    persons_only: false
    min_bbox_area: 100
    max_bbox_overlap: 0.65
    enable_foreground_detections: true
    foreground_kernel_size: 3
    foreground_binary_threshold: 18
    n_velocity_bins: 8
    use_velocity_features: true
    use_pose_features: true
    use_deep_features: true
    n_components_velocity: 5
    n_neighbors_pose: 1
    n_neighbors_deep: 1

task: DETECTION
